# -*- coding: utf-8 -*-
"""02_feature_sets_and_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bjyyxve_gAcIBM6kIhQXxVcGwkxMzn1f
"""

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
import copy

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"

df = pd.read_excel(DATA_DIR / "amphibian_cleaned.xlsx")
print(df.shape)
df.head()

y = df['High_Risk']
print(y.value_counts())

X = df.drop(columns=['High_Risk', 'Species_Name'])
print(X.shape)

TAXONOMY_FEATURES = ['Order', 'Family']

GEOGRAPHY_FEATURES = [
    'Afrotropical', 'Australasian/Oceanian', 'Indomalayan',
    'Nearctic', 'Neotropical', 'Palearctic'
]

BIOLOGY_FEATURES = [
    'Egg_Laying', 'Free_Living_Larval_Stage',
    'Live_Birth', 'Water_Breeding'
]

THREAT_FEATURES = [
    'Agriculture', 'Timber_and_plant_harvesting', 'Infrastructure_development',
    'Pollution', 'Mining_energy_production', 'Water_management',
    'Human_disturbance', 'Geological_Events', 'Over-exploitation',
    'Climate_ongoing', 'Climate_future', 'Fire',
    'Bd_future', 'Bd_ongoing', 'Bsal_future', 'Bsal_ongoing',
    'Invasive_species', 'Natives_species'
]

# --- Leakage note ---
# Target variable: High_Risk (derived from the 2022 Red List assessment)
#
# Excluded entirely:
#   - Species_Name: identifier, not a predictor
#   - Any column directly from the 2022 assessment (Red List category,
#     criteria, extinction flags, 2004-2022 change variables) — these
#     either ARE the label or are generated alongside it, so using them
#     would be direct leakage.
#
# Feature groups kept and why:
#   TAXONOMY:  Order, Family — stable biological classification,
#              fully available before any assessment.
#   GEOGRAPHY: Realm columns — known habitat range, not assessment-derived.
#   BIOLOGY:   Reproductive traits — intrinsic species characteristics,
#              independent of the Red List process.
#   THREAT:    Ecological/human-impact pressures — included as candidate
#              predictors because they represent pressures associated with
#              extinction risk. We acknowledge some threat labels may
#              partially reflect expert assessment, so we test a restricted
#              feature set (Pipeline A) vs. a full set (Pipeline B) to
#              check whether threat variables inflate performance.

PIPELINE_A_FEATURES = TAXONOMY_FEATURES + GEOGRAPHY_FEATURES + BIOLOGY_FEATURES

PIPELINE_B_FEATURES = TAXONOMY_FEATURES + GEOGRAPHY_FEATURES + BIOLOGY_FEATURES + THREAT_FEATURES

PIPELINE_C1_FEATURES = TAXONOMY_FEATURES
PIPELINE_C2_FEATURES = GEOGRAPHY_FEATURES
PIPELINE_C3_FEATURES = BIOLOGY_FEATURES
PIPELINE_C4_FEATURES = THREAT_FEATURES

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"Train: {X_train.shape[0]} rows")
print(f"Test:  {X_test.shape[0]} rows")

def build_preprocessor(feature_list):
    cat_cols = [f for f in feature_list if f in ['Order', 'Family']]
    bin_cols = [f for f in feature_list if f not in ['Order', 'Family']]

    categorical_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
    ])

    binary_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='constant', fill_value=0))
    ])

    transformers = []
    if cat_cols:
        transformers.append(('categorical', categorical_transformer, cat_cols))
    if bin_cols:
        transformers.append(('binary', binary_transformer, bin_cols))

    return ColumnTransformer(transformers=transformers, remainder='drop')

preprocessor_A  = build_preprocessor(PIPELINE_A_FEATURES)
preprocessor_B  = build_preprocessor(PIPELINE_B_FEATURES)
preprocessor_C1 = build_preprocessor(PIPELINE_C1_FEATURES)
preprocessor_C2 = build_preprocessor(PIPELINE_C2_FEATURES)
preprocessor_C3 = build_preprocessor(PIPELINE_C3_FEATURES)
preprocessor_C4 = build_preprocessor(PIPELINE_C4_FEATURES)

print("All preprocessors built successfully")

X_train_A,  X_test_A  = X_train[PIPELINE_A_FEATURES],  X_test[PIPELINE_A_FEATURES]
X_train_B,  X_test_B  = X_train[PIPELINE_B_FEATURES],  X_test[PIPELINE_B_FEATURES]
X_train_C1, X_test_C1 = X_train[PIPELINE_C1_FEATURES], X_test[PIPELINE_C1_FEATURES]
X_train_C2, X_test_C2 = X_train[PIPELINE_C2_FEATURES], X_test[PIPELINE_C2_FEATURES]
X_train_C3, X_test_C3 = X_train[PIPELINE_C3_FEATURES], X_test[PIPELINE_C3_FEATURES]
X_train_C4, X_test_C4 = X_train[PIPELINE_C4_FEATURES], X_test[PIPELINE_C4_FEATURES]

print("All feature splits ready")

# Check 1: class ratio preserved after split
print("Class ratio — full: ", round(y.mean(), 3))
print("Class ratio — train:", round(y_train.mean(), 3))
print("Class ratio — test: ", round(y_test.mean(), 3))

# Check 2: no missing values
print("\nMissing values in X_train:", X_train.isnull().sum().sum())
print("Missing values in X_test: ", X_test.isnull().sum().sum())

# Check 3: shapes look right
print("\nX_train_A shape:", X_train_A.shape)
print("X_train_B shape:", X_train_B.shape)

# Check 4: preprocessor works end to end
# We use a deep copy so preprocessor_B remains unfitted and clean
# for use inside the full model pipelines later.
preprocessor_B_check = copy.deepcopy(preprocessor_B)
X_check = preprocessor_B_check.fit_transform(X_train_B)
print("\nPreprocessor B output shape:", X_check.shape)
print("Preprocessor B working: OK")
