# -*- coding: utf-8 -*-
"""03_baseline_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biLQAIgNsl10XVkF1VGsedK1cHP5mZ8F

# AI Machine Learning Foundations - Project
## Baseline models + first results table

Name: Noor Z, Mohamed E, Tina H, Hamza M, Karim J, Haya Mourad

Course: AI – Machine Learning Foundations  

Professor: Matteo Turilli

Date: May 2026

# Step 3 — Baseline Models

The goal of this section is to run baseline classification models on the cleaned amphibian dataset and produce the first results table for the group.

These results are preliminary holdout benchmarks only. They are not used for final model selection or hyperparameter tuning. Final model selection will be performed using cross-validation inside the training set, and the test set will be used only once at the end for final evaluation.

## Dataset Loading
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import warnings
warnings.filterwarnings("ignore")

"""## Dataset Loading

We use the cleaned amphibian dataset prepared by the previous team steps. The target variable is `High_Risk`, where 1 represents high extinction risk and 0 represents low extinction risk.
"""

df = pd.read_excel("amphibian_cleaned.xlsx")

print("Dataset shape:", df.shape)
print(df.head())
print(df["High_Risk"].value_counts())

print("Target distribution:")
display(df["High_Risk"].value_counts())

print("\nTarget proportions:")
display(df["High_Risk"].value_counts(normalize=True))

"""## Train-Test Split

The dataset is split before fitting any model or preprocessing step. This avoids preprocessing leakage, because imputation and encoding should be learned only from the training data, not from the full dataset.
"""

X = df.drop(columns=["High_Risk", "Species_Name"])
y = df["High_Risk"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

print("\nTrain target distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest target distribution:")
print(y_test.value_counts(normalize=True))

"""## Feature Sets

Following the group pipeline, I evaluate baseline models on two feature sets:

1. Restricted feature set: taxonomy, geography, and biological traits.
2. Full feature set: restricted early-indicator features plus selected human-impact and environmental threat variables.

This allows the group to compare a cleaner early-indicator benchmark against a broader feature set including threat information.
"""

taxonomy_features = [
    "Order",
    "Family"
]

geography_features = [
    "Afrotropical",
    "Australasian/Oceanian",
    "Indomalayan",
    "Nearctic",
    "Neotropical",
    "Palearctic"
]

bio_features = [
    "Egg_Laying",
    "Free_Living_Larval_Stage",
    "Live_Birth",
    "Water_Breeding"
]

threat_features = [
    "Agriculture",
    "Timber_and_plant_harvesting",
    "Infrastructure_development",
    "Pollution",
    "Mining/energy_production",
    "Water_management",
    "Human_disturbance",
    "Geological_Events",
    "Over-exploitation",
    "Climate_(ongoing)",
    "Climate_(future)",
    "Fire",
    "Bd_(future)",
    "Bd_(ongoing)",
    "Bsal_(future)",
    "Bsal_(ongoing)",
    "Invasive_species",
    "Natives_species"
]

restricted_features = taxonomy_features + geography_features + bio_features
full_features = restricted_features + threat_features

feature_sets = {
    "Restricted": restricted_features,
    "Full": full_features
}

for name, features in feature_sets.items():
    print(name, "feature count:", len(features))

"""## Preprocessing

Categorical variables are one-hot encoded, while binary/numeric variables are passed through after imputation. The preprocessing is placed inside a Scikit-learn Pipeline so that transformations are fitted only on the training set.
"""

def build_preprocessor(feature_list):
    categorical_cols = [col for col in feature_list if col in ["Order", "Family"]]
    numeric_cols = [col for col in feature_list if col not in categorical_cols]

    categorical_pipeline = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
    ])

    numeric_pipeline = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value=0))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("categorical", categorical_pipeline, categorical_cols),
            ("numeric", numeric_pipeline, numeric_cols)
        ],
        remainder="drop"
    )

    return preprocessor

"""## Baseline Models

I train several baseline models: Dummy Classifier, Logistic Regression, Decision Tree, Random Forest, and Gradient Boosting. These models give the group a first benchmark before Hamza performs tuning.
"""

from sklearn.ensemble import RandomForestClassifier

models = {
    "Dummy Classifier": DummyClassifier(strategy="most_frequent"),
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),
    "Decision Tree": DecisionTreeClassifier(
        class_weight="balanced",
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

"""## Evaluation function"""

def evaluate_model(model, X_train, X_test, y_train, y_test, feature_list):
    preprocessor = build_preprocessor(feature_list)

    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("model", model)
    ])

    pipeline.fit(X_train[feature_list], y_train)

    y_pred = pipeline.predict(X_test[feature_list])

    if hasattr(pipeline.named_steps["model"], "predict_proba"):
        y_prob = pipeline.predict_proba(X_test[feature_list])[:, 1]
        roc_auc = roc_auc_score(y_test, y_prob)
    else:
        roc_auc = np.nan

    results = {
        "F1": f1_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "ROC-AUC": roc_auc
    }

    return results, pipeline

"""## Run all baseline models"""

all_results = []
trained_pipelines = {}

for feature_set_name, feature_list in feature_sets.items():
    print(f"Running models for feature set: {feature_set_name}")

    for model_name, model in models.items():
        results_dict, pipeline = evaluate_model(
    model,
    X_train,
    X_test,
    y_train,
    y_test,
    feature_list=feature_list
)

        results_dict["Feature Set"] = feature_set_name
        results_dict["Model"] = model_name

        all_results.append(results_dict)

        trained_pipelines[(feature_set_name, model_name)] = pipeline

print("All baseline models finished.")

"""## Results table"""

results_table = pd.DataFrame(all_results)

results_table = results_table[
    [
        "Feature Set",
        "Model",
        "F1",
        "Recall",
        "Precision",
        "ROC-AUC"
    ]
]

results_table = results_table.sort_values(
    by=["Feature Set", "F1"],
    ascending=[True, False]
)

results_table = results_table.round(3)

display(results_table)

"""These results are preliminary holdout benchmarks only. They are not used for final model selection or hyperparameter tuning. Final model selection should be performed using cross-validation inside the training set, and the test set should be used only once at the end for final evaluation.

## Save results
"""

results_table.to_csv("haya_baseline_results.csv", index=False)

print("Saved results as haya_baseline_results.csv")

"""## Baseline Results Interpretation

The baseline models provide the first benchmark for the project. The Dummy Classifier represents the zero-rule baseline because it predicts the majority class without using input features.

The Logistic Regression model provides a simple linear baseline, while Decision Tree, Random Forest, and Gradient Boosting capture non-linear relationships and feature interactions.

The full feature set generally performs better than the restricted set, suggesting that threat-related variables add predictive value for extinction risk.

These results are preliminary and will be used for further hyperparameter tuning and final evaluation.

The results show that models trained on the full feature set consistently outperform those using the restricted set, indicating that threat-related variables significantly improve predictive performance. Among the models, ensemble methods such as Random Forest and Gradient Boosting achieve the highest F1 scores, suggesting that capturing non-linear relationships and feature interactions is important for this classification task.

The full feature set performs much better than the restricted set, suggesting that threat variables provide strong predictive signal. However, these results must be interpreted carefully because some threat indicators may be linked to the same expert assessment process used to assign Red List categories. Therefore, the restricted model is a cleaner early-indicator benchmark, while the full model shows the added predictive value of recorded threat information.

Overall, this section provides valid initial benchmarks, but final conclusions should only be made after cross-validation-based tuning and a single final evaluation on the test set.

### Extra — Baseline Models

For Step 3, I trained baseline classification models on the cleaned amphibian dataset. I used a Dummy Classifier, Logistic Regression, Decision Tree, Random Forest, and Gradient Boosting model. These models were tested on both the restricted feature set and the full feature set.

The purpose of this step was not to tune the models, but to create an initial benchmark for the group. The Dummy Classifier provides the zero-rule baseline, while the other models show whether the available features contain predictive signal for extinction risk.

The resulting table reports F1 score, precision, recall, and ROC-AUC. These results will be used by the next team member for hyperparameter tuning and later by Noor for final evaluation and insights.
"""