# -*- coding: utf-8 -*-
"""final_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydSMBrrqHnGkJNBLORwzz3iafqnvdnc9

#  Amphibian Extinction EDA

## Step 1:  Dataset
"""

import pandas as pd

df = pd.read_excel('amphibian_cleaned.xlsx')
df.head()

"""## Step 2: Overview"""

df.shape
df.info()
df.describe()

"""## Step 3: Columns"""

df.columns

"""#Missing Values"""

missing_counts = df.isnull().sum().sort_values(ascending=False)
missing_percent = (df.isnull().mean() * 100).sort_values(ascending=False)

missing_summary = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_percent": missing_percent
})

missing_summary[missing_summary["missing_count"] > 0]

"""We checked missing values to understand which variables may require imputation before modeling. Missing values will be handled during preprocessing, with categorical variables imputed using the most frequent value and binary indicators filled appropriately."""

df.duplicated().sum()

"""Duplicate rows were checked because repeated observations could bias the model by over-representing certain species.

## Step 4: Target Column (Auto-detect)
"""

possible_targets = [col for col in df.columns if 'status' in col.lower() or 'risk' in col.lower()]

possible_targets

"""## Step 5: Import Libraries"""

import seaborn as sns
import matplotlib.pyplot as plt

"""## Step 6: Histograms"""

df.hist(figsize=(18,14))
plt.show()

"""## Step 7: Correlation"""

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True), cmap='coolwarm')
plt.show()

"""The correlation matrix shows that most features are weakly correlated, meaning they provide distinct information. However, a group of human-related factors such as agriculture, pollution, and infrastructure development shows moderate positive correlation, suggesting these threats often occur together and may collectively increase extinction risk. The presence of moderate correlations among human-impact variables suggests that these threats may co-occur, reinforcing their combined association with high-risk classification.

## Step 8: Target Distribution
"""

TARGET = 'High_Risk'

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x=TARGET, data=df)
plt.title("High Risk Distribution")
plt.show()

"""The distribution confirms that there are more species classified as not high risk than high risk. Despite this imbalance, the dataset still contains a substantial number of high-risk species, allowing meaningful analysis.

#Target percentages
"""

target_counts = df["High_Risk"].value_counts()
target_percent = df["High_Risk"].value_counts(normalize=True) * 100

pd.DataFrame({
    "count": target_counts,
    "percent": target_percent.round(2)
})

"""The target distribution shows a moderate class imbalance. This indicates that evaluation metrics beyond accuracy, such as precision, recall, F1-score, and ROC-AUC, will be important for model assessment."""

df['High_Risk'].value_counts()

"""The target variable shows a moderate class imbalance, with more species classified as not high risk (0) than high risk (1). However, both classes are well represented, making the dataset suitable for classification analysis.

#Step 9: Key Drivers of Extinction Risk
"""

df.select_dtypes(include=['int64','float64']).columns

features = [
    'Agriculture',
    'Pollution',
    'Climate_(ongoing)',
    'Invasive_species',
    'Over-exploitation'
]

for col in features:
    plt.figure()
    sns.barplot(x='High_Risk', y=col, data=df)
    plt.title(f"{col} vs High Risk")
    plt.ylim(0,1)
    plt.show()

"""Agriculture

Species exposed to agricultural pressures show a higher likelihood of being classified as high risk, suggesting that land use changes and habitat modification are associated with higher-risk classification.

Pollution

Pollution is strongly associated with increased extinction risk, as species exposed to environmental contamination are more frequently classified as high risk.

 Climate (ongoing)

Ongoing climate change appears to contribute to higher extinction risk, indicating that changing environmental conditions play a critical role in species vulnerability.

Invasive species

The presence of invasive species is linked to higher extinction risk, likely due to increased competition and ecosystem disruption affecting native species.

Over-exploitation

Over-exploitation is strongly associated with high-risk classification, suggesting that human-driven resource use significantly threatens species survival.

Target explanation

The target variable shows a moderate class imbalance, with more species classified as not high risk than high risk. However, both classes are sufficiently represented, making the dataset suitable for classification analysis

#Grouped means for threat variables
"""

threat_cols = [
    "Agriculture",
    "Pollution",
    "Climate_(ongoing)",
    "Invasive_species",
    "Over-exploitation"
]

df.groupby("High_Risk")[threat_cols].mean().T

"""The grouped means compare the average presence of each threat variable for low-risk and high-risk species. This supports the visual analysis by showing whether high-risk species have higher average exposure to specific threats. Across all threat variables, high-risk species consistently show higher average values, indicating a clear and consistent pattern of increased exposure to environmental and human pressures.

Among the analyzed features, agriculture and pollution appear to show stronger differences between high-risk and low-risk species compared to other variables, suggesting they may be more influential predictors.

#Geography analysis
"""

geo_cols = [
    "Afrotropical",
    "Australasian/Oceanian",
    "Indomalayan",
    "Nearctic",
    "Neotropical",
    "Palearctic"
]

df.groupby("High_Risk")[geo_cols].mean().T

"""Geographic indicators were compared across the target classes to examine whether species from certain regions are more frequently associated with high-risk classification.

# Biology analysis
"""

bio_cols = [
    "Egg_Laying",
    "Free_Living_Larval_Stage",
    "Live_Birth",
    "Water_Breeding"
]

df.groupby("High_Risk")[bio_cols].mean().T

"""Biological traits were compared across risk groups to check whether reproductive or life-stage characteristics are associated with high-risk status.

#**Conclusion**


The EDA suggests that high-risk species tend to show higher average exposure to multiple human-impact and environmental threat indicators, including pollution, agriculture, climate-related pressures, invasive species, and over-exploitation. These factors consistently show stronger associations with high-risk classification. However, these relationships should be interpreted as associations rather than causal effects, as the dataset reflects expert assessments rather than controlled observations.

These findings provide a strong foundation for feature selection and support the use of classification models in the next stage of the project.
"""

# load final cleaned dataset
df = pd.read_excel("amphibian_cleaned.xlsx")

# recreate the SAME split used in modeling (20% test set)
from sklearn.model_selection import train_test_split

_, X_test = train_test_split(df, test_size=0.2, stratify=df['High_Risk'], random_state=42)

# plot class distribution of TEST SET
sns.countplot(x='High_Risk', data=X_test)
plt.title("Class Distribution of Test Set")
plt.xticks([0,1], ['Low Risk','High Risk'])
plt.ylabel("Number of Species")
plt.xlabel("Risk Category")
plt.show()

df['High_Risk'].value_counts()

"""# Feature Sets and Pipeline


"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
import copy

df = pd.read_excel('amphibian_cleaned.xlsx')
print(df.shape)
df.head()

y = df['High_Risk']
print(y.value_counts())

X = df.drop(columns=['High_Risk', 'Species_Name'])
print(X.shape)

TAXONOMY_FEATURES = ['Order', 'Family']

GEOGRAPHY_FEATURES = [
    'Afrotropical', 'Australasian/Oceanian', 'Indomalayan',
    'Nearctic', 'Neotropical', 'Palearctic'
]

BIOLOGY_FEATURES = [
    'Egg_Laying', 'Free_Living_Larval_Stage',
    'Live_Birth', 'Water_Breeding'
]

THREAT_FEATURES = [
    'Agriculture', 'Timber_and_plant_harvesting', 'Infrastructure_development',
    'Pollution', 'Mining/energy_production', 'Water_management',
    'Human_disturbance', 'Geological_Events', 'Over-exploitation',
    'Climate_(ongoing)', 'Climate_(future)', 'Fire',
    'Bd_(future)', 'Bd_(ongoing)', 'Bsal_(future)', 'Bsal_(ongoing)',
    'Invasive_species', 'Natives_species'
]

# --- Leakage note ---
# Target variable: High_Risk (derived from the 2022 Red List assessment)
#
# Excluded entirely:
#   - Species_Name: identifier, not a predictor
#   - Any column directly from the 2022 assessment (Red List category,
#     criteria, extinction flags, 2004-2022 change variables) — these
#     either ARE the label or are generated alongside it, so using them
#     would be direct leakage.
#
# Feature groups kept and why:
#   TAXONOMY:  Order, Family — stable biological classification,
#              fully available before any assessment.
#   GEOGRAPHY: Realm columns — known habitat range, not assessment-derived.
#   BIOLOGY:   Reproductive traits — intrinsic species characteristics,
#              independent of the Red List process.
#   THREAT:    Ecological/human-impact pressures — included as candidate
#              predictors because they represent pressures associated with
#              extinction risk. We acknowledge some threat labels may
#              partially reflect expert assessment, so we test a restricted
#              feature set (Pipeline A) vs. a full set (Pipeline B) to
#              check whether threat variables inflate performance.

PIPELINE_A_FEATURES = TAXONOMY_FEATURES + GEOGRAPHY_FEATURES + BIOLOGY_FEATURES

PIPELINE_B_FEATURES = TAXONOMY_FEATURES + GEOGRAPHY_FEATURES + BIOLOGY_FEATURES + THREAT_FEATURES

PIPELINE_C1_FEATURES = TAXONOMY_FEATURES
PIPELINE_C2_FEATURES = GEOGRAPHY_FEATURES
PIPELINE_C3_FEATURES = BIOLOGY_FEATURES
PIPELINE_C4_FEATURES = THREAT_FEATURES

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"Train: {X_train.shape[0]} rows")
print(f"Test:  {X_test.shape[0]} rows")

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

binary_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value=0))
])

def build_preprocessor(feature_list):
    cat_cols = [f for f in feature_list if f in ['Order', 'Family']]
    bin_cols = [f for f in feature_list if f not in ['Order', 'Family']]

    transformers = []
    if cat_cols:
        transformers.append(('categorical', categorical_transformer, cat_cols))
    if bin_cols:
        transformers.append(('binary', binary_transformer, bin_cols))

    return ColumnTransformer(transformers=transformers, remainder='drop')

preprocessor_A  = build_preprocessor(PIPELINE_A_FEATURES)
preprocessor_B  = build_preprocessor(PIPELINE_B_FEATURES)
preprocessor_C1 = build_preprocessor(PIPELINE_C1_FEATURES)
preprocessor_C2 = build_preprocessor(PIPELINE_C2_FEATURES)
preprocessor_C3 = build_preprocessor(PIPELINE_C3_FEATURES)
preprocessor_C4 = build_preprocessor(PIPELINE_C4_FEATURES)

print("All preprocessors built successfully")

X_train_A,  X_test_A  = X_train[PIPELINE_A_FEATURES],  X_test[PIPELINE_A_FEATURES]
X_train_B,  X_test_B  = X_train[PIPELINE_B_FEATURES],  X_test[PIPELINE_B_FEATURES]
X_train_C1, X_test_C1 = X_train[PIPELINE_C1_FEATURES], X_test[PIPELINE_C1_FEATURES]
X_train_C2, X_test_C2 = X_train[PIPELINE_C2_FEATURES], X_test[PIPELINE_C2_FEATURES]
X_train_C3, X_test_C3 = X_train[PIPELINE_C3_FEATURES], X_test[PIPELINE_C3_FEATURES]
X_train_C4, X_test_C4 = X_train[PIPELINE_C4_FEATURES], X_test[PIPELINE_C4_FEATURES]

print("All feature splits ready")

# Check 1: class ratio preserved after split
print("Class ratio — full: ", round(y.mean(), 3))
print("Class ratio — train:", round(y_train.mean(), 3))
print("Class ratio — test: ", round(y_test.mean(), 3))

# Check 2: no missing values
print("\nMissing values in X_train:", X_train.isnull().sum().sum())
print("Missing values in X_test: ", X_test.isnull().sum().sum())

# Check 3: shapes look right
print("\nX_train_A shape:", X_train_A.shape)
print("X_train_B shape:", X_train_B.shape)

# Check 4: preprocessor works end to end
# We use a deep copy so preprocessor_B remains unfitted and clean
# for use inside the full model pipelines later.
preprocessor_B_check = copy.deepcopy(preprocessor_B)
X_check = preprocessor_B_check.fit_transform(X_train_B)
print("\nPreprocessor B output shape:", X_check.shape)
print("Preprocessor B working: OK")

"""# AI Machine Learning Foundations - Project
## Baseline models + first results table

Name: Noor Z, Mohamed E, Tina H, Hamza M, Karim J, Haya Mourad

Course: AI – Machine Learning Foundations  

Professor: Matteo Turilli

Date: May 2026

# Step 3 — Baseline Models

The goal of this section is to run baseline classification models on the cleaned amphibian dataset and produce the first results table for the group.

These results are preliminary holdout benchmarks only. They are not used for final model selection or hyperparameter tuning. Final model selection will be performed using cross-validation inside the training set, and the test set will be used only once at the end for final evaluation.

## Dataset Loading
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import warnings
warnings.filterwarnings("ignore")

"""## Dataset Loading

We use the cleaned amphibian dataset prepared by the previous team steps. The target variable is `High_Risk`, where 1 represents high extinction risk and 0 represents low extinction risk.
"""

df = pd.read_excel("/content/amphibian_cleaned.xlsx")

print("Dataset shape:", df.shape)
display(df.head())

print("Target distribution:")
display(df["High_Risk"].value_counts())

print("\nTarget proportions:")
display(df["High_Risk"].value_counts(normalize=True))

"""## Train-Test Split

The dataset is split before fitting any model or preprocessing step. This avoids preprocessing leakage, because imputation and encoding should be learned only from the training data, not from the full dataset.
"""

X = df.drop(columns=["High_Risk", "Species_Name"])
y = df["High_Risk"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

print("\nTrain target distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest target distribution:")
print(y_test.value_counts(normalize=True))

"""## Feature Sets

Following the group pipeline, I evaluate baseline models on two feature sets:

1. Restricted feature set: taxonomy, geography, and biological traits.
2. Full feature set: restricted early-indicator features plus selected human-impact and environmental threat variables.

This allows the group to compare a cleaner early-indicator benchmark against a broader feature set including threat information.
"""

taxonomy_features = [
    "Order",
    "Family"
]

geography_features = [
    "Afrotropical",
    "Australasian/Oceanian",
    "Indomalayan",
    "Nearctic",
    "Neotropical",
    "Palearctic"
]

bio_features = [
    "Egg_Laying",
    "Free_Living_Larval_Stage",
    "Live_Birth",
    "Water_Breeding"
]

threat_features = [
    "Agriculture",
    "Timber_and_plant_harvesting",
    "Infrastructure_development",
    "Pollution",
    "Mining/energy_production",
    "Water_management",
    "Human_disturbance",
    "Geological_Events",
    "Over-exploitation",
    "Climate_(ongoing)",
    "Climate_(future)",
    "Fire",
    "Bd_(future)",
    "Bd_(ongoing)",
    "Bsal_(future)",
    "Bsal_(ongoing)",
    "Invasive_species",
    "Natives_species"
]

restricted_features = taxonomy_features + geography_features + bio_features
full_features = restricted_features + threat_features

feature_sets = {
    "Restricted": restricted_features,
    "Full": full_features
}

for name, features in feature_sets.items():
    print(name, "feature count:", len(features))

"""## Preprocessing

Categorical variables are one-hot encoded, while binary/numeric variables are passed through after imputation. The preprocessing is placed inside a Scikit-learn Pipeline so that transformations are fitted only on the training set.
"""

def build_preprocessor(feature_list):
    categorical_cols = [col for col in feature_list if col in ["Order", "Family"]]
    numeric_cols = [col for col in feature_list if col not in categorical_cols]

    categorical_pipeline = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
    ])

    numeric_pipeline = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value=0))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("categorical", categorical_pipeline, categorical_cols),
            ("numeric", numeric_pipeline, numeric_cols)
        ],
        remainder="drop"
    )

    return preprocessor

"""## Baseline Models

I train several baseline models: Dummy Classifier, Logistic Regression, Decision Tree, Random Forest, and Gradient Boosting. These models give the group a first benchmark before Hamza performs tuning.
"""

from sklearn.ensemble import RandomForestClassifier

models = {
    "Dummy Classifier": DummyClassifier(strategy="most_frequent"),
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),
    "Decision Tree": DecisionTreeClassifier(
        class_weight="balanced",
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

"""## Evaluation function"""

def evaluate_model(model, X_train, X_test, y_train, y_test, feature_list):
    preprocessor = build_preprocessor(feature_list)

    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("model", model)
    ])

    pipeline.fit(X_train[feature_list], y_train)

    y_pred = pipeline.predict(X_test[feature_list])

    if hasattr(pipeline.named_steps["model"], "predict_proba"):
        y_prob = pipeline.predict_proba(X_test[feature_list])[:, 1]
        roc_auc = roc_auc_score(y_test, y_prob)
    else:
        roc_auc = np.nan

    results = {
        "F1": f1_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "ROC-AUC": roc_auc
    }

    return results, pipeline

"""## Run all baseline models"""

all_results = []
trained_pipelines = {}

for feature_set_name, feature_list in feature_sets.items():
    print(f"Running models for feature set: {feature_set_name}")

    for model_name, model in models.items():
        results_dict, pipeline = evaluate_model(
    model,
    X_train,
    X_test,
    y_train,
    y_test,
    feature_list=feature_list
)

        results_dict["Feature Set"] = feature_set_name
        results_dict["Model"] = model_name

        all_results.append(results_dict)

        trained_pipelines[(feature_set_name, model_name)] = pipeline

print("All baseline models finished.")

"""## Results table"""

results_table = pd.DataFrame(all_results)

results_table = results_table[
    [
        "Feature Set",
        "Model",
        "F1",
        "Recall",
        "Precision",
        "ROC-AUC"
    ]
]

results_table = results_table.sort_values(
    by=["Feature Set", "F1"],
    ascending=[True, False]
)

results_table = results_table.round(3)

display(results_table)

"""These results are preliminary holdout benchmarks only. They are not used for final model selection or hyperparameter tuning. Final model selection should be performed using cross-validation inside the training set, and the test set should be used only once at the end for final evaluation.

## Save results
"""

results_table.to_csv("haya_baseline_results.csv", index=False)

print("Saved results as haya_baseline_results.csv")

"""## Baseline Results Interpretation

The baseline models provide the first benchmark for the project. The Dummy Classifier represents the zero-rule baseline because it predicts the majority class without using input features.

The Logistic Regression model provides a simple linear baseline, while Decision Tree, Random Forest, and Gradient Boosting capture non-linear relationships and feature interactions.

The full feature set generally performs better than the restricted set, suggesting that threat-related variables add predictive value for extinction risk.

These results are preliminary and will be used for further hyperparameter tuning and final evaluation.

The results show that models trained on the full feature set consistently outperform those using the restricted set, indicating that threat-related variables significantly improve predictive performance. Among the models, ensemble methods such as Random Forest and Gradient Boosting achieve the highest F1 scores, suggesting that capturing non-linear relationships and feature interactions is important for this classification task.

The full feature set performs much better than the restricted set, suggesting that threat variables provide strong predictive signal. However, these results must be interpreted carefully because some threat indicators may be linked to the same expert assessment process used to assign Red List categories. Therefore, the restricted model is a cleaner early-indicator benchmark, while the full model shows the added predictive value of recorded threat information.

Overall, this section provides valid initial benchmarks, but final conclusions should only be made after cross-validation-based tuning and a single final evaluation on the test set.

### Extra — Baseline Models

For Step 3, I trained baseline classification models on the cleaned amphibian dataset. I used a Dummy Classifier, Logistic Regression, Decision Tree, Random Forest, and Gradient Boosting model. These models were tested on both the restricted feature set and the full feature set.

The purpose of this step was not to tune the models, but to create an initial benchmark for the group. The Dummy Classifier provides the zero-rule baseline, while the other models show whether the available features contain predictive signal for extinction risk.

The resulting table reports F1 score, precision, recall, and ROC-AUC. These results will be used by the next team member for hyperparameter tuning and later by Noor for final evaluation and insights.

# Step 4 — Hyperparameter Tuning
**Course:** AI – Machine Learning Foundations  
**Professor:** Matteo Turilli  
**Date:** May 2026

This section performs hyperparameter tuning on the best-performing baseline models (Random Forest and Gradient Boosting) identified in Step 3 (Haya). Tuning is done using RandomizedSearchCV with 5-fold stratified cross-validation, applied only on the training set. The test set is never used during tuning.
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, RandomizedSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import f1_score, recall_score, precision_score, roc_auc_score
from sklearn.metrics import balanced_accuracy_score

"""## Data Loading
We load the cleaned amphibian dataset prepared by the team. The target variable is `High_Risk`, where 1 = high extinction risk and 0 = low extinction risk.
"""

from google.colab import files
uploaded = files.upload()

df = pd.read_excel('amphibian_cleaned.xlsx')

print("Dataset shape:", df.shape)
print("\nTarget distribution:")
print(df['High_Risk'].value_counts())
print("\nTarget proportions:")
print(df['High_Risk'].value_counts(normalize=True).round(3))

"""## Train-Test Split
The dataset is split into 80% training and 20% test before any tuning. The test set is locked away and will only be used once at the very end for final evaluation. Stratification ensures the class ratio is preserved in both sets.
"""

X = df.drop(columns=['High_Risk', 'Species_Name'])
y = df['High_Risk']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print(f"Training set: {X_train.shape}")
print(f"Test set:     {X_test.shape}")
print(f"\nTrain class ratio: {y_train.mean().round(3)}")
print(f"Test class ratio:  {y_test.mean().round(3)}")

"""## Feature Sets
We use the same two feature sets defined by Karim in Step 1:
- **Restricted:** taxonomy + geography + biology only (clean early-indicator benchmark, no leakage risk)
- **Full:** restricted + threat variables (stronger signal but potential leakage from IUCN assessment process)

Tuning is run on both so Noor can compare them in the final evaluation.
"""

taxonomy_features = ['Order', 'Family']

geography_features = [
    'Afrotropical', 'Australasian/Oceanian', 'Indomalayan',
    'Nearctic', 'Neotropical', 'Palearctic'
]

biology_features = [
    'Egg_Laying', 'Free_Living_Larval_Stage',
    'Live_Birth', 'Water_Breeding'
]

threat_features = [
    'Agriculture', 'Timber_and_plant_harvesting', 'Infrastructure_development',
    'Pollution', 'Mining/energy_production', 'Water_management',
    'Human_disturbance', 'Geological_Events', 'Over-exploitation',
    'Climate_(ongoing)', 'Climate_(future)', 'Fire',
    'Bd_(future)', 'Bd_(ongoing)', 'Bsal_(future)', 'Bsal_(ongoing)',
    'Invasive_species', 'Natives_species'
]

restricted_features = taxonomy_features + geography_features + biology_features
full_features = restricted_features + threat_features

print(f"Restricted feature count: {len(restricted_features)}")
print(f"Full feature count:       {len(full_features)}")

"""## Preprocessing Pipeline
Categorical variables (Order, Family) are one-hot encoded. Binary/numeric variables are imputed with 0. All preprocessing is fitted only on the training data inside the pipeline to prevent leakage.
"""

def build_preprocessor(feature_list):
    cat_cols = [c for c in feature_list if c in ['Order', 'Family']]
    num_cols = [c for c in feature_list if c not in cat_cols]

    transformers = []

    if cat_cols:
        transformers.append(('cat', Pipeline([
            ('imp', SimpleImputer(strategy='most_frequent')),
            ('enc', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ]), cat_cols))

    if num_cols:
        transformers.append(('num', SimpleImputer(strategy='constant', fill_value=0), num_cols))

    return ColumnTransformer(transformers=transformers, remainder='drop')
print("Preprocessor ready ")

"""## Hyperparameter Tuning
We tune Random Forest and Gradient Boosting using RandomizedSearchCV with 5-fold stratified cross-validation. Tuning is performed entirely on the training set. The scoring metric is F1, chosen because the dataset has class imbalance and accuracy alone would be misleading.

We use RandomizedSearchCV over GridSearchCV because it covers a broader parameter space efficiently within a reasonable time budget, which is appropriate given our dataset size.
"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

rf_param_grid = {
    'model__n_estimators':      [100, 200, 300],
    'model__max_depth':         [None, 10, 20],
    'model__min_samples_leaf':  [1, 2, 5],
    'model__class_weight':      ['balanced']
}

gbm_param_grid = {
    'model__n_estimators':   [100, 200],
    'model__learning_rate':  [0.05, 0.1, 0.2],
    'model__max_depth':      [3, 5],
    'model__subsample':      [0.8, 1.0],
}

"""## Tuning Random Forest — Restricted Feature Set
This is the clean benchmark model. It uses only taxonomy, geography, and biology features with no leakage risk.
"""

print("Tuning Random Forest on Restricted features")
print("This may take 2-3 minutes")

rf_pipe_restricted = Pipeline([
    ('preprocessor', build_preprocessor(restricted_features)),
    ('model', RandomForestClassifier(random_state=42))
])

rf_search_restricted = RandomizedSearchCV(
    rf_pipe_restricted,
    param_distributions=rf_param_grid,
    n_iter=15,
    scoring='f1',
    cv=cv,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_search_restricted.fit(X_train[restricted_features], y_train)

print("\nDone!")
print(f"Best CV F1:    {rf_search_restricted.best_score_:.3f}")
print(f"Best params:   {rf_search_restricted.best_params_}")

"""## Tuning Gradient Boosting — Restricted Feature Set
Gradient Boosting is tuned on the same restricted feature set for comparison. Unlike Random Forest, GBM does not support class_weight directly — instead we control overfitting through learning rate and subsampling.
"""

print("Tuning Gradient Boosting on Restricted features")
print("This may take 2-3 minutes")

gbm_pipe_restricted = Pipeline([
    ('preprocessor', build_preprocessor(restricted_features)),
    ('model', GradientBoostingClassifier(random_state=42))
])

gbm_search_restricted = RandomizedSearchCV(
    gbm_pipe_restricted,
    param_distributions=gbm_param_grid,
    n_iter=15,
    scoring='f1',
    cv=cv,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

gbm_search_restricted.fit(X_train[restricted_features], y_train)

print("\n Done!")
print(f"Best CV F1:    {gbm_search_restricted.best_score_:.3f}")
print(f"Best params:   {gbm_search_restricted.best_params_}")

"""## Tuning Random Forest — Full Feature Set
The full feature set includes threat variables. As noted in the leakage analysis, these variables may be co-determined with the IUCN assessment process, so results here are expected to be inflated. We include them for comparison purposes only.
"""

print("Tuning Random Forest on Full features")
print("This may take 2-3 minutes")

rf_pipe_full = Pipeline([
    ('preprocessor', build_preprocessor(full_features)),
    ('model', RandomForestClassifier(random_state=42))
])

rf_search_full = RandomizedSearchCV(
    rf_pipe_full,
    param_distributions=rf_param_grid,
    n_iter=15,
    scoring='f1',
    cv=cv,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_search_full.fit(X_train[full_features], y_train)

print("\nDone!")
print(f"Best CV F1:    {rf_search_full.best_score_:.3f}")
print(f"Best params:   {rf_search_full.best_params_}")

"""## Tuning Gradient Boosting — Full Feature Set
Final tuning run. Again, near-perfect scores on the full feature set are expected due to the leakage concern identified earlier.
"""

print("Tuning Gradient Boosting on Full features")
print("This may take 2-3 minutes")

gbm_pipe_full = Pipeline([
    ('preprocessor', build_preprocessor(full_features)),
    ('model', GradientBoostingClassifier(random_state=42))
])

gbm_search_full = RandomizedSearchCV(
    gbm_pipe_full,
    param_distributions=gbm_param_grid,
    n_iter=15,
    scoring='f1',
    cv=cv,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

gbm_search_full.fit(X_train[full_features], y_train)

print("\nDone!")
print(f"Best CV F1:    {gbm_search_full.best_score_:.3f}")
print(f"Best params:   {gbm_search_full.best_params_}")

"""## Results Summary
We evaluate each tuned model on the held-out test set. The best model is selected based on F1 score on the Restricted feature set, as this represents the honest benchmark free from leakage risk.
"""

def evaluate(search, X_test, y_test, feature_list):
    best = search.best_estimator_
    y_pred = best.predict(X_test[feature_list])
    y_prob = best.predict_proba(X_test[feature_list])[:, 1]
    return {
        'Best CV F1':       round(search.best_score_, 3),
        'Test F1':          round(f1_score(y_test, y_pred), 3),
        'Recall':           round(recall_score(y_test, y_pred), 3),
        'Precision':        round(precision_score(y_test, y_pred), 3),
        'ROC-AUC':          round(roc_auc_score(y_test, y_prob), 3),
        'Balanced Acc':     round(balanced_accuracy_score(y_test, y_pred), 3),
    }

results = [
    {'Feature Set': 'Restricted', 'Model': 'Random Forest',     **evaluate(rf_search_restricted,  X_test, y_test, restricted_features)},
    {'Feature Set': 'Restricted', 'Model': 'Gradient Boosting', **evaluate(gbm_search_restricted, X_test, y_test, restricted_features)},
    {'Feature Set': 'Full',       'Model': 'Random Forest',     **evaluate(rf_search_full,         X_test, y_test, full_features)},
    {'Feature Set': 'Full',       'Model': 'Gradient Boosting', **evaluate(gbm_search_full,        X_test, y_test, full_features)},
]

results_df = pd.DataFrame(results)
print(results_df.to_string(index=False))

"""## Comparison with Baseline (Haya's Results)
To measure the impact of tuning, we compare our tuned results against Haya's untuned baseline models on the same feature sets.
"""

baseline = {
    'Feature Set': ['Restricted', 'Restricted', 'Full', 'Full'],
    'Model': ['Random Forest', 'Gradient Boosting', 'Random Forest', 'Gradient Boosting'],
    'Baseline F1': [0.619, 0.565, 0.992, 0.988],
    'Tuned F1':    [0.618, 0.581, 0.992, 0.991],
}

comparison_df = pd.DataFrame(baseline)
comparison_df['Improvement'] = (comparison_df['Tuned F1'] - comparison_df['Baseline F1']).round(3)
print(comparison_df.to_string(index=False))

"""## Best Hyperparameters Discussion

**Random Forest (Restricted):** `max_depth=None` means trees are fully grown, allowing the model to capture complex patterns in the data. `n_estimators=200` provides enough trees for stable predictions. `class_weight=balanced` compensates for the 59/41 class imbalance.

**Gradient Boosting (Restricted):** `learning_rate=0.2` with `max_depth=3` and `subsample=0.8` is a classic combination — shallow trees with moderate learning rate reduces overfitting while subsampling adds randomness for better generalisation.

**Full feature set:** Near-perfect scores (0.99+) on both models confirm the leakage concern. These results are reported for completeness but the Restricted model is the reliable benchmark.

## Tuning Observation
The improvement from tuning is modest on the Restricted feature set. Random Forest showed no meaningful gain (-0.001), suggesting the default settings were already near-optimal for this feature space. Gradient Boosting improved slightly (+0.016).

This is a valid and honest finding. On a structured binary dataset with 12 features, tree-based models can reach near-optimal performance without extensive tuning. The real value of this step is confirming that the baseline results were reliable and not a product of lucky default settings.

## Best Model Selection
On the Restricted feature set, tuned Random Forest achieves the highest F1 (0.618) and ROC-AUC (0.728), making it the selected model for final evaluation. The Full feature set results are noted but treated with caution due to likely leakage from the IUCN assessment process.
"""

import joblib

results_df.to_csv('hamza_tuning_results.csv', index=False)
print("Results saved as hamza_tuning_results.csv")

joblib.dump(rf_search_restricted.best_estimator_,  'best_rf_restricted.pkl')
joblib.dump(gbm_search_restricted.best_estimator_, 'best_gbm_restricted.pkl')
joblib.dump(rf_search_full.best_estimator_,        'best_rf_full.pkl')
joblib.dump(gbm_search_full.best_estimator_,       'best_gbm_full.pkl')
print("All 4 tuned pipelines saved")

from google.colab import files
files.download('hamza_tuning_results.csv')

files.download('best_rf_restricted.pkl')

files.download('best_rf_full.pkl')

files.download('best_gbm_full.pkl')

# Generate test data files for Noor
X_test[restricted_features].to_csv('X_test_restricted.csv', index=False)
X_test[full_features].to_csv('X_test_full.csv', index=False)
y_test.to_csv('y_test.csv', index=False)
print("Test data files ready")

files.download('X_test_restricted.csv')

files.download('X_test_full.csv')

files.download('y_test.csv')

import os
import shutil
import joblib
from google.colab import files

# Create folder
os.makedirs('Hamza_Final_Outputs_For_Noor', exist_ok=True)

# Save all files into the folder
results_df.to_csv('Hamza_Final_Outputs_For_Noor/hamza_tuning_results.csv', index=False)
X_test[restricted_features].to_csv('Hamza_Final_Outputs_For_Noor/X_test_restricted.csv', index=False)
X_test[full_features].to_csv('Hamza_Final_Outputs_For_Noor/X_test_full.csv', index=False)
y_test.to_csv('Hamza_Final_Outputs_For_Noor/y_test.csv', index=False)
joblib.dump(rf_search_restricted.best_estimator_,  'Hamza_Final_Outputs_For_Noor/best_rf_restricted.pkl')
joblib.dump(gbm_search_restricted.best_estimator_, 'Hamza_Final_Outputs_For_Noor/best_gbm_restricted.pkl')
joblib.dump(rf_search_full.best_estimator_,        'Hamza_Final_Outputs_For_Noor/best_rf_full.pkl')
joblib.dump(gbm_search_full.best_estimator_,       'Hamza_Final_Outputs_For_Noor/best_gbm_full.pkl')
print("All 8 files saved to folder")

# Zip and download
shutil.make_archive('Hamza_Final_Outputs_For_Noor', 'zip', 'Hamza_Final_Outputs_For_Noor')
files.download('Hamza_Final_Outputs_For_Noor.zip')
print("Folder downloaded as zip")

"""#Final Evaluation and Interpretation

## Project: Early Indicators of Amphibian Extinction Risk Using Machine Learning

This notebook is the final evaluation and interpretation section of the group project. It uses the final tuned models and test data from Hamza’s tuning notebook to compare model performance, select the final model, interpret the results, and discuss limitations.

# 1. Purpose of This Section

The purpose of this section is to evaluate the final tuned models and decide which model is most appropriate for the project question.

The goal is not only to choose the model with the highest score, but also to decide which model is more reliable and meaningful for identifying early indicators of amphibian extinction risk.

We compare two types of feature sets:

1. Restricted feature set: uses more conservative variables such as taxonomy, geography, and biological traits.
2. Full feature set: includes additional threat-related variables.

The full feature set may produce stronger performance, but it must be interpreted carefully because some threat variables may be closely connected to the Red List assessment process.

# 2. Import Libraries
"""

# If the model files do not load, run this once, then restart runtime:
# !pip install scikit-learn==1.6.1

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    RocCurveDisplay,
    PrecisionRecallDisplay
)

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent if "__file__" in globals() else Path(".")
MODELS_DIR = BASE_DIR / "models"
OUTPUTS_DIR = BASE_DIR / "outputs"

"""# 3. Load Final Models and Test Data

In this section, we load the final tuned models and the matching test datasets.

The files used are:

- best_rf_restricted.pkl
- best_gbm_restricted.pkl
- best_rf_full.pkl
- best_gbm_full.pkl
- hamza_tuning_results.csv
- X_test_restricted.csv
- X_test_full.csv
- y_test.csv
"""

from pathlib import Path

OUTPUTS_DIR = Path("Hamza_Final_Outputs_For_Noor")
MODELS_DIR = OUTPUTS_DIR
tuning_results = pd.read_csv(OUTPUTS_DIR / "hamza_tuning_results.csv")

best_rf_restricted = joblib.load(MODELS_DIR / "best_rf_restricted.pkl")
best_gbm_restricted = joblib.load(MODELS_DIR / "best_gbm_restricted.pkl")
best_rf_full = joblib.load(MODELS_DIR / "best_rf_full.pkl")
best_gbm_full = joblib.load(MODELS_DIR / "best_gbm_full.pkl")

X_test_restricted = pd.read_csv(OUTPUTS_DIR / "X_test_restricted.csv")
X_test_full = pd.read_csv(OUTPUTS_DIR / "X_test_full.csv")
y_test = pd.read_csv(OUTPUTS_DIR / "y_test.csv").squeeze()

"""# 4. Check Data Shapes

Before generating predictions, we check that the test datasets and target variable have matching numbers of rows.
"""

print("X_test_restricted shape:", X_test_restricted.shape)
print("X_test_full shape:", X_test_full.shape)
print("y_test shape:", y_test.shape)

"""The restricted test set contains fewer features because it excludes variables that may be too close to the Red List assessment process. The full test set contains more features because it also includes threat-related variables. Both test sets contain the same number of species, so the model comparison is based on the same evaluation examples.

# 5. Initial Tuning Results

This table shows the final tuning results from the model development stage. It provides an initial comparison of the restricted and full feature-set models.
"""

tuning_results

tuning_results.sort_values(by="Test F1", ascending=False)

"""# 6. Interpretation of Initial Tuning Results

The tuning results show that the full feature-set models achieve almost perfect performance. This suggests that the additional threat-related variables provide very strong predictive information.

However, these results should be interpreted cautiously. Since some threat variables may be connected to the Red List assessment process, the full feature-set models may partially reflect assessment-related information rather than only independent early indicators.

The restricted feature-set models perform more moderately, but they are more conservative. They are more aligned with the main research goal because they rely on biological, taxonomic, and geographic information rather than variables that may be closely tied to the final risk assessment.

# 7. Generate Predictions

After loading the saved models and test datasets, we generate class predictions and predicted probabilities for each model.

The class predictions are used for metrics such as accuracy, precision, recall, F1-score, and the confusion matrix.

The predicted probabilities are used for ROC-AUC, ROC curves, and precision-recall curves.
"""

# Restricted Random Forest
y_pred_rf_restricted = best_rf_restricted.predict(X_test_restricted)
y_proba_rf_restricted = best_rf_restricted.predict_proba(X_test_restricted)[:, 1]

# Restricted Gradient Boosting
y_pred_gbm_restricted = best_gbm_restricted.predict(X_test_restricted)
y_proba_gbm_restricted = best_gbm_restricted.predict_proba(X_test_restricted)[:, 1]

# Full Random Forest
y_pred_rf_full = best_rf_full.predict(X_test_full)
y_proba_rf_full = best_rf_full.predict_proba(X_test_full)[:, 1]

# Full Gradient Boosting
y_pred_gbm_full = best_gbm_full.predict(X_test_full)
y_proba_gbm_full = best_gbm_full.predict_proba(X_test_full)[:, 1]

"""# 8. Final Evaluation Table

This table evaluates all final tuned models on the same test set.

Accuracy is included, but it is not the main metric because it can be misleading when classes are imbalanced. For this project, we focus more on F1-score, recall, precision, ROC-AUC, and balanced accuracy.

Recall is especially important because false negatives mean that a high-risk species was incorrectly classified as low-risk.
"""

def evaluate_model(model_name, y_true, y_pred, y_proba):
    return {
        "Model": model_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1-score": f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_true, y_proba)
    }

final_results = pd.DataFrame([
    evaluate_model("Restricted Random Forest", y_test, y_pred_rf_restricted, y_proba_rf_restricted),
    evaluate_model("Restricted Gradient Boosting", y_test, y_pred_gbm_restricted, y_proba_gbm_restricted),
    evaluate_model("Full Random Forest", y_test, y_pred_rf_full, y_proba_rf_full),
    evaluate_model("Full Gradient Boosting", y_test, y_pred_gbm_full, y_proba_gbm_full)
])

final_results.sort_values(by="F1-score", ascending=False)

"""# 9. Final Evaluation Table Interpretation

The full feature-set models perform best numerically. The Full Random Forest reaches accuracy = 0.994, F1-score = 0.992, recall = 0.984, precision = 1.000, ROC-AUC = 0.996, and balanced accuracy = 0.992.

The Restricted Random Forest performs more moderately, with accuracy = 0.661, F1-score = 0.618, recall = 0.675, precision = 0.571, ROC-AUC = 0.728, and balanced accuracy = 0.663. This suggests that restricted biological, taxonomic, and geographic indicators provide useful but incomplete predictive information.

Because the full model performs almost perfectly, we interpret it cautiously. Some full-set threat variables may be connected to the Red List assessment process, so the Restricted Random Forest is more appropriate for final conservative interpretation.

# 10. Confusion Matrix

The confusion matrix shows the types of errors made by the selected conservative model.

In this project:

- True positive: high-risk species correctly predicted as high-risk.
- False positive: low-risk species incorrectly predicted as high-risk.
- False negative: high-risk species incorrectly predicted as low-risk.
- True negative: low-risk species correctly predicted as low-risk.

False negatives are especially important because they mean the model failed to identify a species that is actually high-risk.
"""

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred_rf_restricted,
    display_labels=["Low risk", "High risk"]
)

plt.title("Confusion Matrix - Restricted Random Forest")
plt.show()

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred_rf_full,
    display_labels=["Low risk", "High risk"]
)

plt.title("Confusion Matrix - Full Random Forest")
plt.show()

"""## Confusion Matrix Interpretation

The Restricted Random Forest correctly classifies 546 low-risk species and 388 high-risk species. It makes 292 false positives and 187 false negatives.

The 187 false negatives are the most concerning errors because they are high-risk species predicted as low-risk. The Full Random Forest performs much better, with 838 correct low-risk predictions, 566 correct high-risk predictions, 0 false positives, and only 9 false negatives.

This confirms that the full feature set is much more predictive, but its near-perfect performance should still be interpreted cautiously.

## Failure Mode Analysis

The main failure mode of the Restricted Random Forest is missing 187 high-risk species and incorrectly flagging 292 low-risk species as high-risk.

This means the restricted feature set can detect many high-risk species, but it does not capture all extinction-risk signals. The model is useful for analysis, but not strong enough to be used alone for real conservation decisions.

# 11. ROC Curve + Interpretation

The Restricted Random Forest has an ROC-AUC of 0.728, shown as approximately 0.73 on the ROC curve. This means it has moderate ability to rank high-risk species above low-risk species.

The Full Random Forest has an ROC-AUC of 0.996, shown as approximately 1.00 on the comparison curve. This indicates almost perfect separation between the two classes, again showing how much predictive power the full feature set adds.
"""

RocCurveDisplay.from_predictions(
    y_test,
    y_proba_rf_restricted
)

plt.title("ROC Curve - Restricted Random Forest")
plt.show()

fig, ax = plt.subplots(figsize=(7, 6))

RocCurveDisplay.from_predictions(
    y_test,
    y_proba_rf_restricted,
    name="Restricted Random Forest",
    ax=ax
)

RocCurveDisplay.from_predictions(
    y_test,
    y_proba_rf_full,
    name="Full Random Forest",
    ax=ax
)

plt.title("ROC Curve Comparison")
plt.show()

"""# 12. Precision-Recall Curve + Interpretation

The Restricted Random Forest has an average precision of approximately 0.63. Its precision decreases as recall increases, meaning that detecting more high-risk species comes with more false positives.

This matches the confusion matrix, where the restricted model predicts 292 low-risk species as high-risk. The Full Random Forest has average precision close to 1.00, meaning it keeps very high precision even at high recall.
"""

PrecisionRecallDisplay.from_predictions(
    y_test,
    y_proba_rf_restricted
)

plt.title("Precision-Recall Curve - Restricted Random Forest")
plt.show()

fig, ax = plt.subplots(figsize=(7, 6))

PrecisionRecallDisplay.from_predictions(
    y_test,
    y_proba_rf_restricted,
    name="Restricted Random Forest",
    ax=ax
)

PrecisionRecallDisplay.from_predictions(
    y_test,
    y_proba_rf_full,
    name="Full Random Forest",
    ax=ax
)

plt.title("Precision-Recall Curve Comparison")
plt.show()

"""# 13. Classification Report + Interpretation
The Restricted Random Forest performs better on low-risk species than high-risk species. For low-risk species, precision = 0.74, recall = 0.65, and F1-score = 0.70.

For high-risk species, precision = 0.57, recall = 0.67, and F1-score = 0.62. This means the model detects about two-thirds of truly high-risk species, but many predicted high-risk cases are actually low-risk.

The Full Random Forest performs almost perfectly, with F1-score = 0.99 for both low-risk and high-risk species.
"""

print("Restricted Random Forest Classification Report")
print(classification_report(
    y_test,
    y_pred_rf_restricted,
    target_names=["Low risk", "High risk"]
))

print("Full Random Forest Classification Report")
print(classification_report(
    y_test,
    y_pred_rf_full,
    target_names=["Low risk", "High risk"]
))

"""The classification report helps identify whether the model is better at recognizing low-risk species or high-risk species. In this project, performance on the high-risk class is especially important because missing high-risk species would be the most serious type of error.

# 14. Feature Importance + Interpretation

The most important restricted features are mainly geographic region indicators, breeding traits, and taxonomic families.

The top features are Australasian/Oceanian importance = 0.085, Water Breeding = 0.070, Free Living Larval Stage = 0.068, Neotropical = 0.061, and Nearctic = 0.046. Several family variables also appear, including Microhylidae = 0.042, Leptodactylidae = 0.040, and Telmatobiidae = 0.037.

This suggests that geography, reproductive ecology, and amphibian family are useful signals for predicting extinction risk. These should be interpreted as predictive associations, not causal effects.
"""

# Automatically find preprocessing step and model step
preprocess_step = list(best_rf_restricted.named_steps.values())[0]
model_step = list(best_rf_restricted.named_steps.values())[-1]

# Get feature names and importances
feature_names = preprocess_step.get_feature_names_out()
importances = model_step.feature_importances_

# Create feature importance table
feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

feature_importance.head(20)

top_features = feature_importance.head(15)

plt.figure(figsize=(10, 6))
plt.barh(top_features["Feature"], top_features["Importance"])
plt.gca().invert_yaxis()
plt.xlabel("Importance")
plt.title("Top 15 Most Important Features - Restricted Random Forest")
plt.show()

"""The most important features provide insight into which taxonomic, biological, or geographic variables were most useful for predicting extinction risk. Because this is the restricted feature set, these variables are less likely to directly encode the Red List assessment outcome.

However, feature importance should be interpreted carefully. It shows predictive usefulness, not causation.

# 15. Final Model Selection

Based only on numerical performance, the Full Random Forest is the strongest model, with F1-score = 0.992 and ROC-AUC = 0.996.

However, we select the Restricted Random Forest as the final conservative model because it better matches the project goal of identifying early indicators. It has lower performance, with F1-score = 0.618 and ROC-AUC = 0.728, but it relies on biological, taxonomic, and geographic features rather than the full threat-variable set.

The full model is still useful as a comparison because it shows that threat-related variables add substantial predictive power.

# 16. Limitations
The main limitation is that the target variable comes from expert-assessed Red List categories, not a direct biological outcome. Also, the full feature set may include variables connected to the assessment process, which could explain the near-perfect Full Random Forest performance: F1-score = 0.992 and ROC-AUC = 0.996.

The restricted model is more conservative, but its performance is moderate: F1-score = 0.618 and ROC-AUC = 0.728. It also misses 187 high-risk species and incorrectly flags 292 low-risk species.

Finally, feature importance shows predictive association, not causation. For example, Australasian/Oceanian and Water Breeding are useful for prediction, but this does not prove they directly cause extinction risk.

# 17. Final Conclusion
The final evaluation shows that machine learning can identify patterns associated with amphibian extinction risk, but results depend strongly on the feature set.

The Full Random Forest performs almost perfectly, with F1-score = 0.992, ROC-AUC = 0.996, 0 false positives, and only 9 false negatives. This suggests that threat variables are highly predictive.

However, the Restricted Random Forest is more appropriate for final interpretation because it uses biological, taxonomic, and geographic indicators and reduces assessment-leakage risk. It reaches F1-score = 0.618 and ROC-AUC = 0.728, showing that restricted early indicators provide useful but incomplete predictive power.
"""